### PR TITLE
Adding option "additionalCode"

### PR DESCRIPTION
**Pull request by mdunisch**
Adding a new feature where you can add additional code to the service-worker.js file.

I needed this to expand the functionality of the original sw-precache-service worker.

### CODE REVIEW

**Comment by cyyyu** [comment]
I'm ok with this but I personally prefer write the additional code in a file. Considering the package.json file cound get very large.

**Comment by mdunisch** [comment]
what do you think about a "parcelsw.rc" file? 
But then we have 2 places to put options

**Comment by cyyyu** [comment]
@mdunisch maybe specify the filename in package.json, and merge them when processing?

**Comment by mdunisch** [comment]
@cyyyu okay i changed this, now there is an option called "additionalCodeFile"

**Comment by mdunisch** [comment]
@cyyyu is this solution finished to merge or do you have anything to change?

**Comment by cyyyu** [comment]
Looks good to me now.

**Comment by mdunisch** [comment]
@cyyyu can you release a new version to npm?

**Comment by cyyyu** [comment]
@mdunisch sure, will do

**Pull request merged**
